### ISSUE TITLE
Zen 1.14b breaks mod

### ISSUE THREAD

**Issue by tsuliwaensis** [mmmintdesign/Zen-Mod-Forbidden-Horizontal-Tabs#17]
Hate to open another issue about this, but version 1.1.4b broke the CSS again.

**Comment by mmmintdesign** [comment]
2a1a3cc301619c3082e438522bc29f5dc64a2f9b should be fixed

**Comment by mmmintdesign** [comment]
6f480dc05ee740f5fa4b6fb7bc3ce7c95e3b8fdc  let me know if this fixes it. I myself don't see the scrollbar for some reason

**Comment by tsuliwaensis** [comment]
I still see the scrollbars, even after removing all the other CSS on my `userChrome.css` and disabling all Zen Mods. It's got to be something with my setup, but I can't track it down.
